# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.5



# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
  allow_failures:

script: phpunit test.php


# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"
